### ISSUE TITLE
Cashier Requirement Installation

### ISSUE THREAD

**Issue by kornatzky** [l4nos/laravel-cashier-stripe-connect#12]
Here is what I see in Laravel 10 project. With cashier just installed:

  Problem 1
    - lanos/laravel-cashier-stripe-connect[1.0.5, ..., 1.0.10] require laravel/cashier ^12.6|^13.4 -> found laravel/cashier[v12.6.0, ..., v12.17.2, v13.4.0, ..., v13.17.0] but it conflicts with your root composer.json require (^14.9).
    - lanos/laravel-cashier-stripe-connect[v1.0.11, ..., v1.0.13] require illuminate/console ^8.37|^9.0 -> found illuminate/console[v8.37.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires lanos/laravel-cashier-stripe-connect * -> satisfiable by lanos/laravel-cashier-stripe-connect[1.0.5, ..., v1.0.13].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require lanos/laravel-cashier-stripe-connect:*" to figure out if any version is installable, or "composer require lanos/laravel-cashier-stripe-connect:^2.1" if you know which you need.

**Comment by kornatzky** [comment]
composer.json:

"laravel/framework": "^10.0",
"laravel/cashier": "^14.9",

**Comment by kornatzky** [comment]
Seems a simple change in the requirements from 14.6 to 14.9 would do it

**Comment by kornatzky** [comment]
on checking it is more complicated

**Comment by kornatzky** [comment]
We get:

    - lanos/laravel-cashier-stripe-connect dev-main requires illuminate/console ^8.37|^9.0|^v10.3.3 -> found illuminate/console[v8.37.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.3.3, 10.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by NickSugden** [comment]
There's a pull request (#8) in that resolves this issue which is requiring @l4nos to merge. 
I did create a fork of this project which you can use while waiting for the merge, or to allow for anyone wanting to validate these changes fix the issue. 
`composer require nicksugden/laravel-cashier-stripe-connect-l10`

**Comment by kornatzky** [comment]
Installation is fine. Thanks for the help again @NickSugden Bravo!

**Comment by madewithrunway** [comment]
I will merge this within 24 hours. Apologies for the delay!

**Comment by phillmorgan28** [comment]
Any update on when this will be merged?

**Comment by l4nos** [comment]
This has been merged. Sorry for the delay, there is a new release too v.1.0.14 which contains "on_behalf_of" functionality on destination charges too.
