### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by jonjakoblich** [l4nos/laravel-cashier-stripe-connect#15]
Hi Robert. Awesome looking package, and I can't wait to dive into it.

The documentation has a bunch of small typos in it. Would you be open to having someone help fix those or would you prefer me to list them all in this issue?

**Comment by l4nos** [comment]
If you can list them. I have a free gitbook account and can't add anyone else to it!

Thanks for pointing any out!

**Comment by l4nos** [comment]
Will update this on next release. Thanks.

**Comment by l4nos** [comment]
Updated
