### ISSUE TITLE
Error al pasar Fecha y Hora a payoutStripeAccount

### ISSUE THREAD

**Issue by miguelalejandrog29** [l4nos/laravel-cashier-stripe-connect#18]
Tengo un error al pasar el segundo parámetro de la función payoutStripeAccount, el correspondiente a la fecha. Me dice que Carbon\Traits\Date no es instanciable. Intento enviar una fecha creada con un objeto de Carbon y me dice que el parámetro que se espera es Carbon\Traits\Date claro está

**Comment by l4nos** [comment]
Lo siento por eso, el tipo de parámetro correcto debería ser una instancia de use Carbon\Carbon. He actualizado el plugin para corregir esto. Por favor, actualiza el plugin y modifica tu código en consecuencia.
