### ISSUE TITLE
Incompatible with latest laravel/cashier package

### ISSUE THREAD

**Issue by BosioGerman** [l4nos/laravel-cashier-stripe-connect#2]
Cannot install this package when you are using the latest laravel/cashier package (v14.x)

it would be spectacular if the dependencies were updated

**Comment by juliancc** [comment]
Any word on this? Just tried to install it and have the same problem. Let me check if it's compatible and nothing breaks. If so,  I will create a PR and see if they accept it

**Comment by juliancc** [comment]
It seems everything works as expected by simply adding v14 to the require. I opened a PR. https://github.com/l4nos/laravel-cashier-stripe-connect/pull/3

**Comment by l4nos** [comment]
Sorry fro the delay, i've been recovering from COVID. I will review your PR now @juliancc thanks for picking this up.

**Comment by l4nos** [comment]
There should be no breaking changes, as a lot of the functionality is independant of Cashier, we only use certain parts of cashier as a dependancy.

**Comment by juliancc** [comment]
@l4nos awesome thanks for merging the PR.. one thing. could you tag the release?  thanks

**Comment by l0gical** [comment]
Any chance this would work with Cashier v15.2
Have just tried installing on a fresh Laravel10 + Cashier and is a no go due to Cashier version
