### ISSUE TITLE
Logic Error: the connected customer does not work

### ISSUE THREAD

**Issue by jasonfish568** [l4nos/laravel-cashier-stripe-connect#20]
```
public function stripeCustomerMapping()
    {
        return $this->belongsTo(ConnectCustomer::class, $this->primaryKey, $this->getLocalIDField())->where('model', '=', get_class($this));
    }
```

A customer can be dealing with multiple merchants. This is assuming that only one record for each customer is stored in the database. This simply means a customer can only deal with one merchant. As it is for connected accounts, the entire logic here breaks. When creating a customer, you recorded the merchant account id but then why here when you retrieve a customer you did not provide the merchant account id? If this is the case, there shouldn't be a pivot mapping table.

**Comment by l4nos** [comment]
The Connected Customer only belongs to one connected account when using Direct Charges (see stripe docs). If you are the merchant of record or are using destination charges (so you are taking payment from the customer then passing in onto the merchant), then you shouldn't use "connected customers" as the customers are technically your customers in the eyes of stripe.

**Comment by jasonfish568** [comment]
As from a platform view, the customer may belong to multiple connected merchant accounts. So how should I find the record in this mapping table?

**Comment by l4nos** [comment]
If a customer belongs to multiple merchant accounts, then the customer actually belongs to you.

A connected customer is a customer that directly transacts with a merchant (not passing through your platform, rahter using direct charges). These customers (within stripe) are owned by the merchant's stripe account, not yours.

If on your platform, you have customers associated with multiple merchants, then you are most likely using destination charges, in which case this plugin will not help you access those customers, you simply use the standard stripe API for accessing those customers directly, or use Vanilla Cashier's customer endpoints.

The mapping table is only for the purpose of mapping customers to merchants that are direct customers of those merchants.

**Comment by l4nos** [comment]
You can read more about these charge types here:


https://stripe.com/docs/connect/direct-charges

https://stripe.com/docs/connect/destination-charges

**Comment by jasonfish568** [comment]
Let me explain the scenario here:

For example I have a model `Customer` and a model `Company` which is the merchant. A `Customer` can purchase books from multiple `Company`. I'm creating a direct charge so the funds gets into the `Company`'s Stripe account. The `Company`'s Stripe account is actually a connected account under my main Stripe account.

```
$checkout_session = $stripe->checkout->sessions->create([
            'line_items' => $line_items,
            'customer' => $customer_id,
            'mode' => 'payment',
            'success_url' => ,
            'cancel_url' => ,
            'client_reference_id' => 'PAYMENT_'.$this->id,
            'invoice_creation' => [
                'enabled' => false
            ],
            'automatic_tax' => [
                'enabled' => $company->is_stripe_tax,
            ],
            'tax_id_collection' => [
                'enabled' => true,
            ],
            'billing_address_collection' => 'required'
        ],['stripe_account' => $connected_account_id]);
```

The mapping table's structure perfectly fits my application. I can have a `Customer` A dealing with multiple `Company`:

|`model`|`model_id`|`model_uuid`|`stripe_customer_id`|`stripe_account_id`|
|---|---|---|---|---|
|App\Models\User|1||cus_123|acc_123|
|App\Models\User|1|cus_456|acc_456|

By using the model_id and the `stripe_account_id`, I can find the stripe_customer_id for this very model under the relative `Company`.

The problem is the `stripeCustomerMapping()` does not provide the `stripe_account_id` so I can't retrieve the correct `stripe_customer_id`.

I'm pretty sure this is called the Direct Charges. Initially I did not use this package but then I found out this package works perfectly on onboarding merchants. But when digging into the payment part, especially trying to keep a record of `User`'s `customer_id`s then the problem came up.

Please let me know your thought.

**Comment by Keiron** [comment]
@jasonfish568 Did you ever make this work - This is the exact scenario I think I need?

**Comment by jasonfish568** [comment]
> @jasonfish568 Did you ever make this work - This is the exact scenario I think I need?

I’m still 100% sure that the logic this repo implemented is wrong. In order to make it work I used only part of the functions. Wherever I need to make a direct charge I wrote my own code. So you just have to maintain your own logic to keep tracking the relationship between the connected customers and all those connected accounts.

I later found that I keep forgetting how I implemented my own code, so make sure you comment your code well. Also, you will need to deeply understand how this entire ecosystem works otherwise you won’t make it work. 

The database structure is totally fine so you don’t have to make any changes to the database I believe.

**Comment by Keiron** [comment]
@jasonfish568 Ah, I've been reviewing it at a database level and it looked like all the data was correctly there, I assume you're just reusing that to create your own direct charge - have you considered forking this repository with your code or is too ingrained into your app?

**Comment by jasonfish568** [comment]
I won’t be able to fork it as we have made our decision not to utilise Stripe anymore. Stripe charges too high, our customers rather do bank transfers to avoid that 80 dollars charge paid to stripe. We also looked into local banks’ products and found that Commonwealth Bank of Australia has a similar product that charges less. If you are not selling globally it’s worth investigating whether there are cheaper local solutions. As you are considering the direct charge I assume you are building a platform. I strongly suggest you reconsider whether Stripe is the best solution for your product. Remember, Stripe charges maximum 4 dollars for each invoice you create using their API, which is ridiculously high when your order volume reaches to a certain level. An in house accountant is only gonna cost around 900 dollars per week in Australia, when don’t I hire someone to do the job off Stripe’s grid? This process can be automated to an extent.
2024年4月25日 +0800 PM11:23 Keiron ***@***.***>，写道：

**Comment by Keiron** [comment]
Ah that's a shame!

We need our direct clients - which is easy with Stripe as normal.
But those clients need to be able to charge their clients through our platform in an automated fashion. Stripe connect looks like the only solution without us holding funds for clients and then dispersing them later.

**Comment by ngl5000** [comment]
I agree, the user can be a customer of multiple merchants on a platform. I might try to fork this and see if I can implement it

**Comment by jasonfish568** [comment]
My team is maintaining payment functions in our project. I suddenly realized, that if the repo owner is developing a SaaS app, that for each Company(for example) has its own Customers, these Customers don't belong to any other Companies. Hence one Customer to One Merchant Account.

But still, ngl5000 summarised clearly that a user can be multiple merchants' customer.

**Comment by l4nos** [comment]
If you wish to fork this and butcher it to your own needs so be it. But let be super clear for you all.

When adopting a DIRECT charges model, Stripe will make the customer exist multiple times in each connected account as they are DIRECT CUSTOMERS OF THE MERCHANT! Your platform will run into issues if you proceed wihtout this fundamental understanding.

@ngl5000 if you want help with this, I can help you, I would hate to see you waste time developing the wrong functionality only to come to the same realisation that i've been trying to share with you. If you want to have assistnace with this, please reach out directly, i'd be happy to screenshare and look at your code.

Jason, the logic of this plugin is correct, i've validated it with stripe themselves. I wouldn't release functionality that wasn't correct.

I'm removing you from this repository as you seem to be constantly spreading misinformation that is undermining the efforts of this plugin and also encouraging poor development practices. Not on my watch.

**Comment by jasonfish568** [comment]
Sorry but this is a discussion? Not sharing misleading info. At least let me share my feedback after your detailed explanation?

**Comment by l4nos** [comment]
A discussion is not what this has become, you are explicitly discreding the plugin and disagreeing with universal facts.

<img width="547" alt="image" src="https://github.com/user-attachments/assets/2f1336d2-5b37-4d54-b800-1fa692a1fb37">

And as a result of this, you've encouraged another user to embark on a wasted endeavour of trying to develop against stripe functionality.

You can have a master customer exist once in your database, but the individual customer mappings which have the traits on need to exist once per merchant. As the customers DIRECTLY transact with said merchant and not your platform.

The best way to achieve this with the plugin and without forking is simply to do the below.

So you'd have a Customer::class modal, then MerchantCustomer::class model with the StripeCustomer mapping for each merchannt, this would have the trait.

`
class Customer extends Model{

    public function merchantCustomerRecords(){
        return $this->hasMany(MerchantCustomer::class);
    }

    protected $table = 'customers';

}

class MerchantCustomer extends Model{

    use ConnectCustomer;

    protected $table = 'merchant_customers';

}
`

Then you would end up with a table structure similar to what Jason explained. The logic of the plugin isn't wrong, it doesn't need forking or butchering, it just needs correct implementation.

**Comment by l4nos** [comment]
@Keiron your solution is also possible with the plugin as is. I'm happy to assist if you're stuck with implementation.

**Comment by ngl5000** [comment]
@l4nos I appreciate the offer to help. I think I've come to the realization a while ago that you were right and changed my approach. I don't need any help at the moment. Thanks!

**Comment by jasonfishblu** [comment]
A repo owner raging on discussion and ban other developers for sharing different opinions? How many users can you ban? Shame on you. No one has to use your plugin to make things work. But when others open up issues, they are contributing to the repo to make it better. Make it private if you don't want to hear other voices.

I must share the correct information with other developers. You are the one spreading misleading information.

---

The problem was never about Stripe's connected customer, everyone understands how Stripe works here. It was only about the trait you designed. It's NOT about Direct Charge or Destination Charge. 

A Customer belongs to the Merchant when using Direct Charge. So it will have its own customer_id with that Merchant. When creating payments, you must provide the related customer_id to the Connected Account. You keep arguing over this point and no one has ever questioned it. It is clearly explained in the Docs.

I have clearly explained the database structure in my previous post. In your post, you mentioned MerchantCustomer. But why can't you use Customer directly? stripe_connected_customer_mapping is already a one to many relationship. Why would you add another layer which is definitely not necessary.

model | model_id | model_uuid | stripe_customer_id | stripe_account_id
-- | -- | -- | -- | --
App\Models\Customer | 1 |   | cus_123 | acc_123
App\Models\Customer | 1 |   | cus_456 | acc_456

You still have individual customer_id with each merchant.

**With your current design, customers on eBay when purchasing with different merchants, they need to register multiple accounts.** Why? Because a customer can only belong to one merchant(And of course I know eBay has Paypal and they don't use Stripe). Think about it. **You need 100 accounts to make purchases with 100 merchants.**

The conclusion is, there is nothing wrong with Stripe or the database structure of this plugin. The only thing that needs to be improved is allowing Customer to have multiple records in stripe_connected_customer_mapping.

**Comment by jasonfishblu** [comment]
If you still don't understand what is wrong. Move stripe_customer_id and stripe_account_id to customers table. Drop stripe_connected_customer_mapping table. Rewrite stripeCustomerMapping() to get stripe_customer_id and stripe_account_id from customers table. Your plugin still works.

**Comment by l4nos** [comment]
The fact you created another account to just to further trash talk me on a closed issue is absurd. I'll remove you as many times as needed until you get the message.

**Comment by l4nos** [comment]
Deleting this thread as it's caused more confusion and contention than was worth.
