### ISSUE TITLE
Add Unit tests

### ISSUE THREAD

**Issue by gogl92** [l4nos/laravel-cashier-stripe-connect#23]
As a developer I'd like to be able to know if my changes are working and it doesn't affect other functionalities.

- Add PHP unit
- Add tests for current functionalities

**Comment by l4nos** [comment]
Will review this shortly along with your other PR and test on local env. If all good, will merge this in.

Thanks for your contributions!

**Comment by gogl92** [comment]
> Will review this shortly along with your other PR and test on local env. If all good, will merge this in.
> 
> Thanks for your contributions!

Thank you, let me know if you have any questions, I think this one can be merged before so we have tests already in place

**Comment by l4nos** [comment]
Unit tests will be out of date now due to change made. Closing for now, if new tests are built i'll merge them in, I don't have time to write them myself at the moment.

**Comment by gogl92** [comment]
@l4nos I'll take a look at what have changed I don't think the tests I added were affected but let me check, I think we need to keep an issue open for the testing but close the PR, I'll create a new one based on the changes.

**Comment by gogl92** [comment]
@l4nos can you please reopen this ticket?
