### ISSUE TITLE
Laravel10 Cashier 15.2

### ISSUE THREAD

**Issue by l0gical** [l4nos/laravel-cashier-stripe-connect#26]
Hi all,

Does anyone happen to know if this will work with the above, or need a lot of modification due to the Stripe Api version?
Trying to avoid reinventing the wheel.
Enviroment PHP8.2, Fresh install of Laravel10 + Cashier v15.2

Thanks in advance.

**Comment by miagg** [comment]
Same question, though Cashier version is now v15.3.

**Comment by l0gical** [comment]
Tried it, enough works to assume it will, then came up against silly
issues, docs are quite lacking too.
Ditched it and decided to write my own from scratch, more work but less
headache as a result.

**Comment by miagg** [comment]
@l0gical so this is a no go?
https://github.com/l4nos/laravel-cashier-stripe-connect/compare/main...Jamiedekloet:laravel-cashier-stripe-connect:main

**Comment by l0gical** [comment]
@miagg Sadly not for me no, some of the functions work which will give you the false sense that all is good, then when you do something like get payment methods, change a price or anything like that, plenty of errors, did look through the code to fix it for 15.3, but decided to write my own custom solution.
Handy tip, just stick with Cashier, use the Stripe ApI docs to make your own methods, make an event listener for the Cashier Webhooks and you have your own solution, which you wrote and can easily tweak to suit future versions.
The GitBook made matters even worse, either incredibly slow or offline when studying the docs (facepalm)

**Comment by miagg** [comment]
Thanks @l0gical , I guess I'll have to rewrite some functions too!

**Comment by l4nos** [comment]
l0gical is right, you can just use the cashier stripe client to make your own methods, however the idea of this plugin is to save you time in doing that and provide you with the models and mappings you need to make this work quickly.

I'll update the plugin this weekend, apologies for the delay, i'm a CTO spread quite thin currently, and i'm only doing this in my spare time as a way of giving back. It should just be a case of fixing any broken functions that may have been changed or deprecated in the Stripe API. If anyone has already done this I will hapilly review and accept a PR, otherwise I'll get to it this weekend.

As for GitBook, i cant help if that is slow or unresponsive, i'm not gitbook, i'd suggest logging a support case with them if you are having trouble accessing the docs.

**Comment by miagg** [comment]
@l4nos I was afraid to ask since I understand you are busy but I if you think you can handle it, it could be a life saver since it could take considerably less time than me submitting a PR.

**Comment by l4nos** [comment]
That's fine, i'll push an update over the weekend.

**Comment by l4nos** [comment]
Ok the release is about to go out, i've done a PR which includes:

- Composer dependency vesrion updates
- Fixed UUID connected accounts not creating properly
- Removed automatic publishing of migraitons in-line with Cashier 15's approach

I've tested this by doing the following:

Building out a basic boilerplate API with Merchant and Customer models.

Then testing:

- Create connected account
- Create connected account customer
- Products
- Prices
- Create direct charge
- Create destination charge

They all seem to work fine.

I'm removing l0gical from the repo as his comments are unhelpful, unkind and unprofessional.

To anyone else who has issues with the plugin, I kindly as that you please record the issue then either offer to contribute via a PR or wait paitently for a fix. Taking to various threads on here and leaving derogatory comments about the plugin is not helpful to anyone and not reflective of the github community guidelines.

**Comment by miagg** [comment]
@l4nos excellent! I will test thoroughly and provide feedback. Thanks a lot for this. 🙏

**Comment by l4nos** [comment]
Thanks @miagg ! If you could kindly log any issues you find sepeately please noting the function / trait name that you encountered the issue on that would be appreciated.
