### ISSUE TITLE
Support for Laravel 11 Cashier 15.x

### ISSUE THREAD

**Issue by ngl5000** [l4nos/laravel-cashier-stripe-connect#27]
Is anyone working on getting this ready for the latest version of Laravel?

**Comment by l0gical** [comment]
I've abandoned using it and about 80% of the way through writing my own
from scratch, maybe that is an option for you, judging by updates and time
it takes to get responses on issues, I think it's either abandoned or real
low priority, if that's the case then I totally get it, it's provided free

**Comment by l4nos** [comment]
Hi guys ,sorry i haven't abandoned, i'm a CTO of a software company doing this in my spare time to support people.

I'll spend some time this weekend making the necessary updates.

**Comment by l4nos** [comment]
Update pushing out now. See latest PR
