### ISSUE TITLE
destination charges rounding precision should be 0

### ISSUE THREAD

**Issue by F-Yousri** [l4nos/laravel-cashier-stripe-connect#29]
`application_fee_amount `is expected to be an integer however it's rounded with precision 2 in `CanCharge` trait in `createDestinationCharge` function.

```
// APPLY PLATFORM FEE COMMISSION - SET THIS AGAINST THE MODEL
        if (isset($this->commission_type) && isset($this->commission_rate)) {
            if ($this->commission_type === 'percentage') {
                $options['application_fee_amount'] = round($this->calculatePercentageFee($amount),2);
            } else {
                $options['application_fee_amount'] = round($this->commission_rate ,2);
            }
        }

        return PaymentIntent::create($options, $this->stripeAccountOptions());
```

for example, if the charge is 3 USD and the commission is 5% it results in error 
```
Stripe\Exception\InvalidRequestException

Invalid integer: 15.75
```

Happy to write a pr if what I am suggesting is correct

**Comment by l4nos** [comment]
You are correct, all amounts in stripe are in cent base (pennies (UK), cents etc). So a decimal would cause an issue here.

A round up would be most appropriate (ceil).

Happy for you to PR or i can do it on Sunday.

**Comment by ngl5000** [comment]
@F-Yousri are you going to put a PR up for this? I'd also benefit from it

**Comment by F-Yousri** [comment]
sorry for the late response I was away from my pc for a while.
@l4nos in direct ``` createDirectCharge``` function your rounding to the nearest integer. I'd recommend doing the same with destination charges or changing both to ceil. Also what do if the user sets a constant float for commission (not percentage say 0.5 thinking it means 0.5 USD and not cents). I'd suggest an exception in that case to tell the user.

I'll submit a pr with ceil for destination charges as you suggested anyways and leave the rest for you to decide

**Comment by l4nos** [comment]
Hi @F-Yousri thanks for your response on this.

I'll approve the PR shortly, I think an |invalid commission rate" exception should be added in, I'll do that following the PR and put it out as a new composer release shortly.

Thanks for your help with this.
