### ISSUE TITLE
Compatibility with Stripe web elements

### ISSUE THREAD

**Issue by GeorgeWillis** [l4nos/laravel-cashier-stripe-connect#38]
Apologies if this is the wrong place to ask this question but is there out of the box compatibility with Stripe web elements?

I have used the following to create and retrieve the client secret from a connected account 
`->createDirectCharge(5000, 'GBP')->client_secret` but when i pass this into the `stripe.elements` in js i get an error 
`The client_secret provided does not match any associated PaymentIntent on this account`.

I'm guessing i am missing a step or is this even possible?

Thanks in advance.

**Comment by GeorgeWillis** [comment]
I managed to get working using the following https://docs.stripe.com/connect/direct-charges?platform=web&ui=elements if anyone has this trouble in the future.

**Comment by l4nos** [comment]
Glad you got it working.

For anyone else struggling with direct charges and UI elements, you have to inject the connected accounts ID into the config on intialisation, otherwise it initialises as the "platform" which means only destination charges will work.
