### ISSUE TITLE
Update doc link

### ISSUE THREAD

**Issue by chrisvasey** [l4nos/laravel-cashier-stripe-connect#4]
Hello!

Loving the package, it has been an absolute lifesaver for me.

One small thing that I couldn't PR but thought might be worth pointing out, could you update the doc link on the left-hand side of the Github page to point your [updated docs in the readme](https://updev-1.gitbook.io/cashier-for-connect/)?
<img width="376" alt="Screenshot 2022-12-15 at 16 40 22" src="https://user-images.githubusercontent.com/7483460/207917933-676e1141-abcd-49dd-8ebe-451dcaf002bb.png">

This caught me out a few times when I accidentally opened the docs from the old repo and not found what I need.

All the best!

**Comment by l4nos** [comment]
Hi Chris,

Thanks for the kind words, hopefully this package has saved you as much time as it's saved me.

I've updated the link now. The old link was from the original forked package.

If you have any other issues or questions regarding the package let me know. Hopefully the readme I wrote has been helpful in explaining the core concepts the package aims to deal with.
