### ISSUE TITLE
Cashier requirement on installation

### ISSUE THREAD

**Issue by cpraught** [l4nos/laravel-cashier-stripe-connect#5]
Hi,

Laravel cashier has been updated to 14.6, which means that Composer no longer supports the installation :

Problem 1
    - Root composer.json requires lanos/laravel-cashier-stripe-connect ^1.0 -> satisfiable by lanos/laravel-cashier-stripe-connect[1.0.5, ..., 1.0.10].
    - lanos/laravel-cashier-stripe-connect[1.0.5, ..., 1.0.10] require laravel/cashier ^12.6|^13.4 -> found laravel/cashier[v12.6.0, ..., 12.x-dev, v13.4.0, ..., 13.x-dev] but it conflicts with your root composer.json require (^14.6).

**Comment by l4nos** [comment]
There are no breaking changes from what I can see. Updated the composer.json and pushed new release out.

Please let me know if there are any issues.
