### ISSUE TITLE
Documentation changes

### ISSUE THREAD

**Issue by DougThwaites** [l4nos/laravel-cashier-stripe-connect#6]
Hi @l4nos,

Firstly thanks heaps for keeping this package alive and improving upon it :)

I would like to contribute to the docs and was wondering if you could point me in the right direction to do so?

Specifically on the [onboarding-accounts](https://updev-1.gitbook.io/cashier-for-connect/setting-up-models/onboarding-accounts) page change the handle on boarding method from:

`
    private function handleBoardingRedirect(Store $Store): RedirectResponse
    {
        // Redirect to dashboard if onboarding is already completed.
        if ($store->hasStripeAccountId() && $store->hasCompletedOnboarding()) {
            return $store->redirectToAccountDashboard();
        }

        // Delete account if already exists and create new express account with 
        // weekly payouts.
        $store->deleteAndCreateStripeAccount('express', [
            'settings' => [
                'payouts' => [ 
                    'schedule' => [ 
                        'interval' => 'weekly', 
                        'weekly_anchor' => 'friday',
                    ]
                ]
            ]
        ]);

        // Redirect to Stripe account onboarding, with return and refresh url, otherwise.
        return $store->redirectToAccountOnboarding(
            URL::to('/api/stripe/return?api_token=' . $store->api_token),
            URL::to('/api/stripe/refresh?api_token=' . $store->api_token)
        );
    }
`

to:

`
    private function handleBoardingRedirect(Store $Store): RedirectResponse
    {
        // Redirect to dashboard if onboarding is already completed.
        if ($store->hasStripeAccount() && $store->hasCompletedOnboarding()) {
            return $store->redirectToAccountDashboard();
        }

        // Delete account if already exists and create new express account with 
        // weekly payouts.
        $store->deleteAndCreateStripeAccount('express', [
            'settings' => [
                'payouts' => [ 
                    'schedule' => [ 
                        'interval' => 'weekly', 
                        'weekly_anchor' => 'friday',
                    ]
                ]
            ]
        ]);

        // You may wish/need to refresh your billable model as it has been deleted and recreated
        $store->refresh();

        // Redirect to Stripe account onboarding, with return and refresh url, otherwise.
        return $store->redirectToAccountOnboarding(
            URL::to('/api/stripe/return?api_token=' . $store->api_token),
            URL::to('/api/stripe/refresh?api_token=' . $store->api_token)
        );
    }
`

The two changes are:

1. Swapping out hasStripeAccountId() for hasStripeAccount() as hasStripeAccountId() doesn't exist.
2. Suggesting optionally the user may want to refresh their connect billable model to get the new account id correctly amongst other things

For point 2. around refreshing the billable model this could also be done by the package after the new mapping is created but I am wary of refreshing a model without the developer explicitly knowing but open to thoughts there on more seasoned users of this package?

Hope this helps, apologies if I've missed something I am new to the package.

Have a good one :)

**Comment by l4nos** [comment]
Hi @DougThwaites,

Thanks for the kind words and I'm glad to see you've gained a lot of value from the package.

Great spots on the documentation. I'll update shortly the incorrect function reference and whilst I would hope most developers looking to use the package would be well versed in reloading relationships, I agree that it may be something overlooked. I'll action that change also shortly.

Thanks,
Rob

**Comment by l4nos** [comment]
Updated

**Comment by DougThwaites** [comment]
Thanks @l4nos, if you need any certain contributions please reach out, I am more than happy to help :)
